version: "3.9"

services:
  db:
    image: postgres:15
    container_name: period_db
    environment:
      POSTGRES_USER: perioduser
      POSTGRES_PASSWORD: periodpass
      POSTGRES_DB: periodtracker
    ports:
      - "5433:5432"
